# Generated by Django 2.0.3 on 2018-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('sender', models.CharField(max_length=1024)),
                ('receiver', models.CharField(max_length=1024)),
                ('is_read', models.BooleanField(default=0)),
                ('date', models.DateTimeField(verbose_name='date wrote')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=1024)),
            ],
        ),
    ]
